name: Build Unreal Engine Project

on:
  push:
    branches:
      - main  # Укажите основную ветку вашего проекта

jobs:
  build:
    runs-on: [self-hosted]  # Запуск на собственном агенте

    steps:
   # - name: Checkout Repository
   #   uses: actions/checkout@v2
    - name: Build Project
      shell: pwsh
      run: |
       [string]$UEPath = "C:\Program Files\Epic Games\UE_5.3"
       [string]$ProjectPath = "$pwd"
       Start-Process -FilePath "$UEPath\Engine\Build\BatchFiles\RunUAT.bat" -ArgumentList BuildPlugin, -project="$PROJECT_PATH" -TargetPlatforms=Win64,-package="$ProjectPath\PluginBuild"," > BuildPluginLog.txt" -Wait -NoNewWindow -PassThru
