name: Build Unreal Engine Project
on:
  push:
    branches:
      - main  # Укажите основную ветку вашего проекта
jobs:
  build:
    runs-on: [self-hosted]  # Запуск на собственном агенте
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup Unreal Engine
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Укажите версию Python, если требуется для настройки Unreal Engine
    - name: Build Project
      run: |
        $UE_PATH/Engine/Build/BatchFiles/RunUAT.bat BuildCookRun -project="$PROJECT_PATH" -noP4 -platform="Win64" -clientconfig="Development" -serverconfig="Development" -cook -allmaps -build -stage -pak -archive
      env:
        UE_PATH: ${{ secrets.UE_PATH }}  # Путь к движку Unreal Engine (задайте его в секретах репозитория)
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}  # Путь к проекту Unreal Engine (задайте его в секретах репозитория)
