name: Build Unreal Engine Project

on:
  push:
    branches:
      - main  # Укажите основную ветку вашего проекта

jobs:
  build:
    runs-on: [self-hosted]  # Запуск на собственном агенте

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Build Project
      shell: cmd
      env: 
        UE_PATH: 'C:\Program Files\Epic Games\UE_5.3'
        UPROJECT_PATH: ${{ github.workspace }}/MyProject.uproject
        PLATFORMS: Win64
        CONFIGURATION: Development
        ARCHIVE_PATH: ${{ github.workspace }}/build
      run: |
        "%UE_PATH%\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun -Project="%UPROJECT_PATH%" -noP4 -TargetPlatforms="%PLATFORMS%" -clientconfig="%CONFIGURATION%" -build -cook -stage -pak -archive -archivedirectory="%ARCHIVE_PATH%"
