name: Build Unreal Engine Project
on:
  push:
    branches:
      - main  # Укажите основную ветку вашего проекта
jobs:
  build:
    runs-on: [self-hosted]  # Запуск на собственном агенте
    steps:
   # - name: Checkout Repository
    #  uses: actions/checkout@v2
    - name: Build Project
      run: |
        '%UE_ROOT%/Engine/Build/BatchFiles/RunUAT.bat' BuildCookRun -project=C:\test\devops-test\DevopsTest.uproject -noP4 -platform=Win64 -clientconfig=Development -build -cook -stage -pak -archive -archivedirectory=$(Build.StagingDirectory)
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: built-files  # Имя для артефакта
        path: 'C:\123'


